### ISSUE TITLE
Upgrade request is made to the Angular localhost instead of target server

### ISSUE THREAD

**Issue by MariuszPL55** [yurivoronin/ngx-signalr-websocket#2]
Hello,

I think there is a bug because after the handshake the library wants to call an angular app instead of the target server. I am creating client like this:
```TypeScript
const client = SignalrClient.create(httpClient);

client.connect(`hubs/${connectionPath}`).subscribe({
	next: (connection) => {
		this.connection = connection;
		initCallback();
	},
	error: (error) => console.error(error)
});
```

On the screen, you can see that the first request is made correctly but the second one is going to `:4200` which is an Angular app.
![image](https://github.com/user-attachments/assets/07ccf3d5-fde7-4bdd-876b-dd0e7cf6abf2)

I am using an interceptor for `HttpClient` to redirect to a good URL so I think the second request is not passing through the http client interceptor.

**Comment by yurivoronin** [comment]
Hi!

By design, it is supposed to pass the target SignalR hub URL to the `client.connect()` method. Angular **HttpClient** is only used for handshake, so the interceptor only affects it.

**HttpClient** is not designed to work with the WebSocket protocol. For a WebSocket connection, [RxJS WebSocket](https://rxjs.dev/api/webSocket/webSocket) is used, but the interceptor does not interact with it.

Tell more about your case, why the interceptor is used to change the URL host, maybe we can find a solution.

**Comment by MariuszPL55** [comment]
Yes, that's correct about HttpClient for HTTP and WebSocket for WebSocket connections. So we need to approach it without an interceptor in this case. Let's close this issue.
